exports.data = {
	htype:'住宅',				
	rtype:'整租',
	projname:'',
	projcode:'',
	district:'请选择',	
	comarea:'请选择商圈',	
	address:'',	
	
	room:'',
	hall:'',
	toilet:'',
	area:'',
	floor:'',
	totalFloor:'',
	price:'',
	checkIndate:(function(){
		var date = new Date()
		return date.toLocaleDateString().split('/').join('-');
	}()),	
	title:'',
	description:'',
	imgurl:[],
	titleimg:'',
	username:'',
	usermobile:'',
	houseType:[
		{text:'住宅'},
		{text:'别墅'},
		{text:'写字楼'},
		{text:'商铺'}
	],
	rentType:[
		{text:'整租'},
		{text:'合租'}					
	],
	fitments:[
		{text:'豪华装修'},
		{text:'精装修'},
		{text:'中等装修'},
		{text:'简装修'},
		{text:'毛坯'}
	],
	fitment:'豪华装修',
	forwards:[
		{text:'请选择'},
		{text:'南北'},
		{text:'南'},
		{text:'东南'},
		{text:'东'},
		{text:'西南'},
		{text:'北'},
		{text:'西'},
		{text:'东西'},
		{text:'东北'},
		{text:'西北'}
	],
	forward:'请选择',
	payinfos:[
		{text:'押一付三'},
		{text:'押一付二'},
		{text:'押一付一'},
		{text:'押二付一'},
		{text:'半年付'},
		{text:'年付'},
		{text:'面议'}					
	],
	payinfo:'面议',
	equitments:{
		rent:[
			{text:'床',done:false},
			{text:'宽带',done:false},
			{text:'电视',done:false},
			{text:'冰箱',done:false},
			{text:'洗衣机',done:false},
			{text:'空调',done:false},
			{text:'热水器',done:false},
			{text:'暖气',done:false}	
		],		
		villa:[
			{text:'车库',done:false},
			{text:'露台',done:false},
			{text:'游泳池',done:false},
			{text:'阁楼',done:false},
			{text:'阳光房',done:false},
			{text:'车位',done:false}	
		],		
		shop:[
			{text:'客梯',done:false},
			{text:'货梯',done:false},
			{text:'停车位',done:false},
			{text:'暖气',done:false},
			{text:'空调',done:false},
			{text:'网络',done:false}	
		],

	},
	equitment:'',
	rentways:[
		{text:'主卧'},
		{text:'次卧'},
		{text:'床位'},
		{text:'单间'}	
	],
	rentway:'次卧',
	partners:[
		{text:'2'},
		{text:'3'},
		{text:'4'},
		{text:'5'},
		{text:'6'}			
	],
	partner:'请选择合租户数',
	genders:[
		{text:'性别不限'},
		{text:'限男生'},
		{text:'限女生'},
		{text:'限夫妻'}	
	],
	gender:'性别不限',
	priceTypes:[
		{text:'元/平米·天'},
		{text:'元/平米·月'},
		{text:'元/月'},
	],
	priceType:'元/月',
	hits:[], // 楼盘联想
	localArea:[], // 区县数据
	localComa:[],  // 商圈数据
	localComaItem:[],	
	// 写字楼相关字段		
	officeTypes:[
		{text:'纯写字楼'},
		{text:'商住楼'},
		{text:'商业综合体楼'},
		{text:'酒店写字楼'}	
	],
	officeType:'请选择类型',
	officeGrades:[
		{text:'甲级'},
		{text:'乙级'},
		{text:'丙级'}
	],
	officeGrade:'请选择级别',
	officePayinfos:[
		{text:'面议'},
		{text:'月付'},
		{text:'季付'},
		{text:'半年付'},
		{text:'年付'}		
	],	
	ofloor:'',
	ototalFloor:'',
	oarea:'',
	oprice:'',
	wuyefei:'',
	wuyecompany:'',
	iswuyefei:'包含',
	iswuyefeis:[
		{text:'包含'},
		{text:'不包含'}
	],
	issplit:'',
	issplits:[
		{text:'可分割'},
		{text:'不可分割'}
	],
	limitdate:'',
	limitdates:[
		{text:'7'},
		{text:'15'},
		{text:'30'},
		{text:'60'}
	],
	// 商铺相关字段
	shopTypes:[
		{text:'住宅底商'},
		{text:'商业街商铺'},
		{text:'临街门面'},
		{text:'写字楼配套底商'},
		{text:'购物中心/百货'},
		{text:'其他'}		
	],
	shopType:'请选择类型',
	shopGrades:[
		{text:'商铺出租'},
		{text:'商铺转让'}		
	],
	shopGrade:'请选择类别',
	shopPayinfos:[
		{text:'面议'},
		{text:'月付'},
		{text:'季付'},
		{text:'半年付'},
		{text:'年付'}	
	],	
	sfloor:'',
	stotalFloor:'',
	sarea:'',
	sprice:'',
	manageCategorys:[
		{text:'餐饮美食',done:false},
		{text:'服饰鞋包',done:false},
		{text:'休闲娱乐',done:false},
		{text:'美容美发',done:false},
		{text:'生活服务',done:false},
		{text:'百货超市',done:false},
		{text:'酒店宾馆',done:false},
		{text:'家具建材',done:false},
		{text:'其他',done:false}
	],
	manageCategory:'',
	shopStates:[
		{text:'营业中',value:0},
		{text:'闲置中',value:1},
		{text:'新铺',value:2}
	],
	shopState:'0',
	isuse400:''
}